let marketQuotesConfig = null;

async function loadMarketQuotes() {
  const root = document.getElementById('market-quotes-root');

  try {
    const response = await fetch('./generated/dashboard.json');

    if (!response.ok) {
      throw new Error(`HTTP ${response.status}`);
    }

    marketQuotesConfig = await response.json();

    await loadFilters(marketQuotesConfig);

    renderWidgets();
  } catch (error) {
    console.error('Failed to load generated/dashboard.json', error);

    root.innerHTML = `
      <div class="col-12">
        <div class="alert alert-danger">
          Cannot load <code>generated/dashboard.json</code>. It is generated by GitHub Actions (<code>.github/workflows/deploy.yml</code>) via <code>npm run build:data</code>.
        </div>
      </div>
    `;
  }
}

function renderWidgets() {
  const root = document.getElementById('market-quotes-root');

  if (!root || !marketQuotesConfig) {
    return;
  }

  const groups = marketQuotesConfig?.groups || [];
  const filteredWidgets = filterWidgets(marketQuotesConfig?.widgets || []);

  const symbolsGroups = groups
    .map((groupName) => {
      const groupSymbols = filteredWidgets
        .filter((widget) => (widget.groups || []).includes(groupName))
        .map((widget) => ({
          name: widget.symbol,
          displayName: widget.title || widget.symbol
        }));

      const seen = new Set();

      const uniqueSymbols = groupSymbols.filter((item) => {
        if (seen.has(item.name)) {
          return false;
        }

        seen.add(item.name);
        return true;
      });

      return {
        name: groupName,
        symbols: uniqueSymbols
      };
    })
    .filter((group) => group.symbols.length > 0);

  if (symbolsGroups.length === 0) {
    root.innerHTML = `
      <div class="col-12">
        <div class="alert alert-secondary">
          No symbols found in <code>generated/dashboard.json</code>.
        </div>
      </div>
    `;

    return;
  }

  root.innerHTML = `
    <div class="col-12">
      <div class="card shadow-sm">
        <div class="card-body">
          <div class="tradingview-widget-container">
            <div id="market-quotes-widget" class="tradingview-widget-container__widget"></div>
            <div class="tradingview-widget-copyright">
              <a href="https://www.tradingview.com/markets/" rel="noopener nofollow" target="_blank">
                <span class="blue-text">Market summary</span>
              </a>
              <span class="trademark"> by TradingView</span>
            </div>
          </div>
        </div>
      </div>
    </div>
  `;

  const widgetContainer = document.getElementById('market-quotes-widget');

  if (!widgetContainer) {
    return;
  }

  const script = document.createElement('script');
  script.type = 'text/javascript';
  script.src = 'https://s3.tradingview.com/external-embedding/embed-widget-market-quotes.js';
  script.async = true;

  script.text = JSON.stringify({
    colorTheme: 'dark',
    locale: 'en',
    largeChartUrl: 'index.html',
    isTransparent: false,
    showSymbolLogo: true,
    backgroundColor: '#212529',
    width: '100%',
    height: 720,
    symbolsGroups,
    support_host: 'https://www.tradingview.com'
  });

  widgetContainer.appendChild(script);
}

loadMarketQuotes();
